<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'postal_code' => 'AF'],
            ['name' => 'Albania', 'postal_code' => 'AL'],
            ['name' => 'Algeria', 'postal_code' => 'DZ'],
            ['name' => 'Andorra', 'postal_code' => 'AD'],
            ['name' => 'Angola', 'postal_code' => 'AO'],
            ['name' => 'Antigua and Barbuda', 'postal_code' => 'AG'],
            ['name' => 'Argentina', 'postal_code' => 'AR'],
            ['name' => 'Armenia', 'postal_code' => 'AM'],
            ['name' => 'Australia', 'postal_code' => 'AU'],
            ['name' => 'Austria', 'postal_code' => 'AT'],
            ['name' => 'Azerbaijan', 'postal_code' => 'AZ'],
            ['name' => 'Bahamas', 'postal_code' => 'BS'],
            ['name' => 'Bahrain', 'postal_code' => 'BH'],
            ['name' => 'Bangladesh', 'postal_code' => 'BD'],
            ['name' => 'Barbados', 'postal_code' => 'BB'],
            ['name' => 'Belarus', 'postal_code' => 'BY'],
            ['name' => 'Belgium', 'postal_code' => 'BE'],
            ['name' => 'Belize', 'postal_code' => 'BZ'],
            ['name' => 'Benin', 'postal_code' => 'BJ'],
            ['name' => 'Bhutan', 'postal_code' => 'BT'],
            ['name' => 'Bolivia', 'postal_code' => 'BO'],
            ['name' => 'Bosnia and Herzegovina', 'postal_code' => 'BA'],
            ['name' => 'Botswana', 'postal_code' => 'BW'],
            ['name' => 'Brazil', 'postal_code' => 'BR'],
            ['name' => 'Brunei', 'postal_code' => 'BN'],
            ['name' => 'Bulgaria', 'postal_code' => 'BG'],
            ['name' => 'Burkina Faso', 'postal_code' => 'BF'],
            ['name' => 'Burundi', 'postal_code' => 'BI'],
            ['name' => 'Cabo Verde', 'postal_code' => 'CV'],
            ['name' => 'Cambodia', 'postal_code' => 'KH'],
            ['name' => 'Cameroon', 'postal_code' => 'CM'],
            ['name' => 'Canada', 'postal_code' => 'CA'],
            ['name' => 'Central African Republic', 'postal_code' => 'CF'],
            ['name' => 'Chad', 'postal_code' => 'TD'],
            ['name' => 'Chile', 'postal_code' => 'CL'],
            ['name' => 'China', 'postal_code' => 'CN'],
            ['name' => 'Colombia', 'postal_code' => 'CO'],
            ['name' => 'Comoros', 'postal_code' => 'KM'],
            ['name' => 'Congo (Congo-Brazzaville)', 'postal_code' => 'CG'],
            ['name' => 'Congo (Congo-Kinshasa)', 'postal_code' => 'CD'],
            ['name' => 'Costa Rica', 'postal_code' => 'CR'],
            ['name' => 'Croatia', 'postal_code' => 'HR'],
            ['name' => 'Cuba', 'postal_code' => 'CU'],
            ['name' => 'Cyprus', 'postal_code' => 'CY'],
            ['name' => 'Czechia', 'postal_code' => 'CZ'],
            ['name' => 'Denmark', 'postal_code' => 'DK'],
            ['name' => 'Djibouti', 'postal_code' => 'DJ'],
            ['name' => 'Dominica', 'postal_code' => 'DM'],
            ['name' => 'Dominican Republic', 'postal_code' => 'DO'],
            ['name' => 'Ecuador', 'postal_code' => 'EC'],
            ['name' => 'Egypt', 'postal_code' => 'EG'],
            ['name' => 'El Salvador', 'postal_code' => 'SV'],
            ['name' => 'Equatorial Guinea', 'postal_code' => 'GQ'],
            ['name' => 'Eritrea', 'postal_code' => 'ER'],
            ['name' => 'Estonia', 'postal_code' => 'EE'],
            ['name' => 'Eswatini', 'postal_code' => 'SZ'],
            ['name' => 'Ethiopia', 'postal_code' => 'ET'],
            ['name' => 'Fiji', 'postal_code' => 'FJ'],
            ['name' => 'Finland', 'postal_code' => 'FI'],
            ['name' => 'France', 'postal_code' => 'FR'],
            ['name' => 'Gabon', 'postal_code' => 'GA'],
            ['name' => 'Gambia', 'postal_code' => 'GM'],
            ['name' => 'Georgia', 'postal_code' => 'GE'],
            ['name' => 'Germany', 'postal_code' => 'DE'],
            ['name' => 'Ghana', 'postal_code' => 'GH'],
            ['name' => 'Greece', 'postal_code' => 'GR'],
            ['name' => 'Grenada', 'postal_code' => 'GD'],
            ['name' => 'Guatemala', 'postal_code' => 'GT'],
            ['name' => 'Guinea', 'postal_code' => 'GN'],
            ['name' => 'Guinea-Bissau', 'postal_code' => 'GW'],
            ['name' => 'Guyana', 'postal_code' => 'GY'],
            ['name' => 'Haiti', 'postal_code' => 'HT'],
            ['name' => 'Honduras', 'postal_code' => 'HN'],
            ['name' => 'Hungary', 'postal_code' => 'HU'],
            ['name' => 'Iceland', 'postal_code' => 'IS'],
            ['name' => 'India', 'postal_code' => 'IN'],
            ['name' => 'Indonesia', 'postal_code' => 'ID'],
            ['name' => 'Iran', 'postal_code' => 'IR'],
            ['name' => 'Iraq', 'postal_code' => 'IQ'],
            ['name' => 'Ireland', 'postal_code' => 'IE'],
            ['name' => 'Israel', 'postal_code' => 'IL'],
            ['name' => 'Italy', 'postal_code' => 'IT'],
            ['name' => 'Jamaica', 'postal_code' => 'JM'],
            ['name' => 'Japan', 'postal_code' => 'JP'],
            ['name' => 'Jordan', 'postal_code' => 'JO'],
            ['name' => 'Kazakhstan', 'postal_code' => 'KZ'],
            ['name' => 'Kenya', 'postal_code' => 'KE'],
            ['name' => 'Kiribati', 'postal_code' => 'KI'],
            ['name' => 'Kuwait', 'postal_code' => 'KW'],
            ['name' => 'Kyrgyzstan', 'postal_code' => 'KG'],
            ['name' => 'Laos', 'postal_code' => 'LA'],
            ['name' => 'Latvia', 'postal_code' => 'LV'],
            ['name' => 'Lebanon', 'postal_code' => 'LB'],
            ['name' => 'Lesotho', 'postal_code' => 'LS'],
            ['name' => 'Liberia', 'postal_code' => 'LR'],
            ['name' => 'Libya', 'postal_code' => 'LY'],
            ['name' => 'Liechtenstein', 'postal_code' => 'LI'],
            ['name' => 'Lithuania', 'postal_code' => 'LT'],
            ['name' => 'Luxembourg', 'postal_code' => 'LU'],
            ['name' => 'Madagascar', 'postal_code' => 'MG'],
            ['name' => 'Malawi', 'postal_code' => 'MW'],
            ['name' => 'Malaysia', 'postal_code' => 'MY'],
            ['name' => 'Maldives', 'postal_code' => 'MV'],
            ['name' => 'Mali', 'postal_code' => 'ML'],
            ['name' => 'Malta', 'postal_code' => 'MT'],
            ['name' => 'Marshall Islands', 'postal_code' => 'MH'],
            ['name' => 'Mauritania', 'postal_code' => 'MR'],
            ['name' => 'Mauritius', 'postal_code' => 'MU'],
            ['name' => 'Mexico', 'postal_code' => 'MX'],
            ['name' => 'Micronesia', 'postal_code' => 'FM'],
            ['name' => 'Moldova', 'postal_code' => 'MD'],
            ['name' => 'Monaco', 'postal_code' => 'MC'],
            ['name' => 'Mongolia', 'postal_code' => 'MN'],
            ['name' => 'Montenegro', 'postal_code' => 'ME'],
            ['name' => 'Morocco', 'postal_code' => 'MA'],
            ['name' => 'Mozambique', 'postal_code' => 'MZ'],
            ['name' => 'Myanmar', 'postal_code' => 'MM'],
            ['name' => 'Namibia', 'postal_code' => 'NA'],
            ['name' => 'Nauru', 'postal_code' => 'NR'],
            ['name' => 'Nepal', 'postal_code' => 'NP'],
            ['name' => 'Netherlands', 'postal_code' => 'NL'],
            ['name' => 'New Zealand', 'postal_code' => 'NZ'],
            ['name' => 'Nicaragua', 'postal_code' => 'NI'],
            ['name' => 'Niger', 'postal_code' => 'NE'],
            ['name' => 'Nigeria', 'postal_code' => 'NG'],
            ['name' => 'North Korea', 'postal_code' => 'KP'],
            ['name' => 'North Macedonia', 'postal_code' => 'MK'],
            ['name' => 'Norway', 'postal_code' => 'NO'],
            ['name' => 'Oman', 'postal_code' => 'OM'],
            ['name' => 'Pakistan', 'postal_code' => 'PK'],
            ['name' => 'Palau', 'postal_code' => 'PW'],
            ['name' => 'Panama', 'postal_code' => 'PA'],
            ['name' => 'Papua New Guinea', 'postal_code' => 'PG'],
            ['name' => 'Paraguay', 'postal_code' => 'PY'],
            ['name' => 'Peru', 'postal_code' => 'PE'],
            ['name' => 'Philippines', 'postal_code' => 'PH'],
            ['name' => 'Poland', 'postal_code' => 'PL'],
            ['name' => 'Portugal', 'postal_code' => 'PT'],
            ['name' => 'Qatar', 'postal_code' => 'QA'],
            ['name' => 'Romania', 'postal_code' => 'RO'],
            ['name' => 'Russia', 'postal_code' => 'RU'],
            ['name' => 'Rwanda', 'postal_code' => 'RW'],
            ['name' => 'Saint Kitts and Nevis', 'postal_code' => 'KN'],
            ['name' => 'Saint Lucia', 'postal_code' => 'LC'],
            ['name' => 'Saint Vincent and the Grenadines', 'postal_code' => 'VC'],
            ['name' => 'Samoa', 'postal_code' => 'WS'],
            ['name' => 'San Marino', 'postal_code' => 'SM'],
            ['name' => 'Sao Tome and Principe', 'postal_code' => 'ST'],
            ['name' => 'Saudi Arabia', 'postal_code' => 'SA'],
            ['name' => 'Senegal', 'postal_code' => 'SN'],
            ['name' => 'Serbia', 'postal_code' => 'RS'],
            ['name' => 'Seychelles', 'postal_code' => 'SC'],
            ['name' => 'Sierra Leone', 'postal_code' => 'SL'],
            ['name' => 'Singapore', 'postal_code' => 'SG'],
            ['name' => 'Slovakia', 'postal_code' => 'SK'],
            ['name' => 'Slovenia', 'postal_code' => 'SI'],
            ['name' => 'Solomon Islands', 'postal_code' => 'SB'],
            ['name' => 'Somalia', 'postal_code' => 'SO'],
            ['name' => 'South Africa', 'postal_code' => 'ZA'],
            ['name' => 'South Korea', 'postal_code' => 'KR'],
            ['name' => 'South Sudan', 'postal_code' => 'SS'],
            ['name' => 'Spain', 'postal_code' => 'ES'],
            ['name' => 'Sri Lanka', 'postal_code' => 'LK'],
            ['name' => 'Sudan', 'postal_code' => 'SD'],
            ['name' => 'Suriname', 'postal_code' => 'SR'],
            ['name' => 'Sweden', 'postal_code' => 'SE'],
            ['name' => 'Switzerland', 'postal_code' => 'CH'],
            ['name' => 'Syria', 'postal_code' => 'SY'],
            ['name' => 'Taiwan', 'postal_code' => 'TW'],
            ['name' => 'Tajikistan', 'postal_code' => 'TJ'],
            ['name' => 'Tanzania', 'postal_code' => 'TZ'],
            ['name' => 'Thailand', 'postal_code' => 'TH'],
            ['name' => 'Timor-Leste', 'postal_code' => 'TL'],
            ['name' => 'Togo', 'postal_code' => 'TG'],
            ['name' => 'Tonga', 'postal_code' => 'TO'],
            ['name' => 'Trinidad and Tobago', 'postal_code' => 'TT'],
            ['name' => 'Tunisia', 'postal_code' => 'TN'],
            ['name' => 'Turkey', 'postal_code' => 'TR'],
            ['name' => 'Turkmenistan', 'postal_code' => 'TM'],
            ['name' => 'Tuvalu', 'postal_code' => 'TV'],
            ['name' => 'Uganda', 'postal_code' => 'UG'],
            ['name' => 'Ukraine', 'postal_code' => 'UA'],
            ['name' => 'United Arab Emirates', 'postal_code' => 'AE'],
            ['name' => 'United Kingdom', 'postal_code' => 'GB'],
            ['name' => 'United States', 'postal_code' => 'US'],
            ['name' => 'Uruguay', 'postal_code' => 'UY'],
            ['name' => 'Uzbekistan', 'postal_code' => 'UZ'],
            ['name' => 'Vanuatu', 'postal_code' => 'VU'],
            ['name' => 'Vatican City', 'postal_code' => 'VA'],
            ['name' => 'Venezuela', 'postal_code' => 'VE'],
            ['name' => 'Vietnam', 'postal_code' => 'VN'],
            ['name' => 'Yemen', 'postal_code' => 'YE'],
            ['name' => 'Zambia', 'postal_code' => 'ZM'],
            ['name' => 'Zimbabwe', 'postal_code' => 'ZW'],
        ];

        // Insert countries into the database
        DB::table('countries')->insert($countries);
    }
}
